# Las matemáticas tras la regresión lineal

### Tablas de contingencia

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("/content/drive/MyDrive/Machine Learning - Python/Datasets - Machine Learning/gender-purchase/Gender Purchase.csv")

In [4]:
data.head()

   Gender Purchase
0  Female      Yes
1  Female      Yes
2  Female       No
3    Male       No
4    Male      Yes

In [7]:
data.shape

(511, 2)

In [8]:
contingency_table = pd.crosstab(data['Gender'], data['Purchase'])
contingency_table

Purchase   No  Yes
Gender
Female    106  159
Male      125  121

In [9]:
contingency_table.sum(axis = 0) # Suma en eje vertical

Purchase
No     231
Yes    280
dtype: int64

In [10]:
contingency_table.sum(axis = 1) # Suma en eje horizontal

Gender
Female    265
Male      246
dtype: int64

In [15]:
# Por ejemplo, si la persona que entra es mujer, existe un 60% de probabilidad de que compre

contingency_table.astype('float').div(contingency_table.sum(axis = 1), axis = 0)

Purchase       No      Yes
Gender
Female    0.40000  0.60000
Male      0.50813  0.49187

## La probabilidad condicional

* Cuál es la probabilidad de que un cliente compre un producto, sabiendo que es hombre?

In [17]:
"""
Total de hombres en la observación = 125 + 121 = 246
Total de hombres que compraron = 125
P = 121 / 246
"""

121 / 246

0.491869918699187

* Cuál es la probabilidad de que una compra realizada, haya sido por una mujer?

In [18]:
"""
Total de mujeres que compraron = 159
Total de personas que compraron = 159 + 121 = 280
P = 159 / 280
"""
159 / 280

0.5678571428571428

### Probabilidades que pueden ser de interés (ver el comando): `contingency_table.astype('float').div(contingency_table.sum(axis = 1), axis = 0)`:

* Probabilidad de que siendo mujer, compre = 60%
* Probabilidad de que siendo mujer, no compre = 40%
* Probabilidad de que siendo hombre, compre = 49%
* Probabilidad de que siendo hombre, no compre = 51%

## Ratio de probabilidades:
### Es el cociente de los casos de éxito entre los casos de fracaso en el suceso estudiado y para cada grupo.

* Pm = probabilidad de comprar, siendo hombre.
* Pf = probabilidad de comprar, siendo mujer.

### Según las tablas anteriores:

* Pm = 121 / 246
* Pf = 159 / 265


## Entonces:

* Cm = Pm / (1 - Pm)
* Cf = Pf / (1 - Pf)

In [19]:
'''
Pm = probabilidad de comprar, siendo hombre.
Pf = probabilidad de comprar, siendo mujer.

Pm = 121 / 246
Pf = 159 / 265

odds_m ~ Cm
odds_f ~ Cf
'''

pm = 121 / 246
pf = 159 / 265

odds_m = pm / (1 - pm)
odds_f = pf / (1 - pf)

print(odds_m)
print(odds_f)

0.9680000000000002
1.4999999999999998